"""initial commit

Revision ID: da9f339e883b
Revises: 
Create Date: 2020-08-10 22:50:45.014313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da9f339e883b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('luck_special', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('improvement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('move',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('move_class', sa.Integer(), nullable=True),
    sa.Column('rating', sa.String(length=8), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('char_class', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('harm', sa.Integer(), nullable=True),
    sa.Column('luck', sa.Integer(), nullable=True),
    sa.Column('charm', sa.Integer(), nullable=True),
    sa.Column('cool', sa.Integer(), nullable=True),
    sa.Column('sharp', sa.Integer(), nullable=True),
    sa.Column('tough', sa.Integer(), nullable=True),
    sa.Column('weird', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_name'), 'character', ['name'], unique=False)
    op.create_table('class_improvements',
    sa.Column('improvement_id', sa.Integer(), nullable=True),
    sa.Column('character_class', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_class'], ['character_class.id'], ),
    sa.ForeignKeyConstraint(['improvement_id'], ['improvement.id'], )
    )
    op.create_table('character__note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_improvements',
    sa.Column('improvement_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['improvement_id'], ['improvement.id'], )
    )
    op.create_table('character_moves',
    sa.Column('move_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['move_id'], ['move.id'], )
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('tags', sa.String(length=64), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_name'), 'item', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_name'), table_name='item')
    op.drop_table('item')
    op.drop_table('character_moves')
    op.drop_table('character_improvements')
    op.drop_table('character__note')
    op.drop_table('class_improvements')
    op.drop_index(op.f('ix_character_name'), table_name='character')
    op.drop_table('character')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('move')
    op.drop_table('improvement')
    op.drop_table('character_class')
    # ### end Alembic commands ###
